import { nanoid } from 'nanoid'
import type { CharacterBible, EmotionalPaletteTag, VisualPersonalityTag } from '@/types/character'
import type { PromptBlock } from '@/types/prompt'
import type { WorkflowStage, StageId } from '@/types/workflow'
import { STAGE_EXTRACTION_RULES, STAGE_DEFINITIONS } from '@/data/stageTemplates'
import { resolveFieldPath } from '@/lib/resolveFieldPath'

const emotionalPaletteLabels: Record<EmotionalPaletteTag, string> = {
  serious: 'serio',
  smiling: 'sonriente',
  melancholic: 'melancólico',
  aggressive: 'agresivo',
  mysterious: 'misterioso',
  elegant: 'elegante',
  innocent: 'inocente',
  dark: 'sombrío',
  playful: 'juguetón',
  stoic: 'estoico',
  passionate: 'apasionado',
  serene: 'sereno',
}

const visualPersonalityLabels: Record<VisualPersonalityTag, string> = {
  elegant: 'elegante',
  dark: 'oscuro',
  chaotic: 'caótico',
  heroic: 'heroico',
  villain: 'villanesco',
  mystical: 'místico',
  military: 'militar',
  technological: 'tecnológico',
  natural: 'natural',
  minimalist: 'minimalista',
  ornate: 'ornamentado',
}

export function buildCharacterContext(character: CharacterBible): string {
  const parts: string[] = []
  const g = character.general
  const a = character.appearance

  if (character.name) parts.push(character.name)

  const identity = [
    g.species,
    g.profession,
  ].filter(Boolean).join(' ')
  if (identity) parts.push(identity)

  const physique = [g.height, g.weight, g.constitution].filter(Boolean).join(', ')
  if (physique) parts.push(physique)

  const hair = [a.hair?.style, a.hair?.color].filter(Boolean).join(' ')
  if (hair) parts.push('cabello ' + hair)

  const eyes = [a.eyes?.shape, a.eyes?.color].filter(Boolean).join(' ')
  if (eyes) parts.push('ojos ' + eyes)

  if (a.skinColor) parts.push('piel ' + a.skinColor)
  if (a.faceShape) parts.push('rostro ' + a.faceShape)
  if (a.beard) parts.push('barba ' + a.beard)
  if (a.mustache) parts.push('bigote ' + a.mustache)
  if (a.scars) parts.push('cicatrices: ' + a.scars)
  if (a.tattoos) parts.push('tatuajes: ' + a.tattoos)

  if (character.emotionalPalette?.length) {
    parts.push(character.emotionalPalette.map((tag) => emotionalPaletteLabels[tag]).join(', '))
  }
  if (character.visualPersonality?.length) {
    parts.push(character.visualPersonality.map((tag) => visualPersonalityLabels[tag]).join(', '))
  }
  if (character.references?.hasReferences) {
    parts.push('imagen de referencia disponible')
  }

  return parts.join(', ')
}

export function autoGenerateBlocksForStage(
  character: CharacterBible,
  stageId: StageId
): PromptBlock[] {
  const rules = STAGE_EXTRACTION_RULES.filter((r) => r.stageId === stageId)
  const blocks: PromptBlock[] = []
  let order = 0

  for (const rule of rules) {
    const value = resolveFieldPath(character, rule.fieldPath)
    if (value && value.trim()) {
      blocks.push({
        id: nanoid(),
        category: rule.category,
        label: rule.label,
        value: value.trim(),
        order: order++,
        enabled: true,
      })
    }
  }

  return blocks
}

export function createEmptyStages(): WorkflowStage[] {
  return STAGE_DEFINITIONS.map((def) => ({
    id: def.id,
    index: def.index,
    blocks: [],
    customText: '',
    negativePrompt: '',
    generatedPrompt: '',
    isAutoGenerated: false,
    updatedAt: Date.now(),
  }))
}

export function autoPopulateAllStages(
  character: CharacterBible
): WorkflowStage[] {
  return STAGE_DEFINITIONS.map((def) => {
    const blocks = autoGenerateBlocksForStage(character, def.id)
    return {
      id: def.id,
      index: def.index,
      blocks,
      customText: '',
      negativePrompt: '',
      generatedPrompt: '',
      isAutoGenerated: true,
      updatedAt: Date.now(),
    }
  })
}

export function generateStagePrompt(
  blocks: PromptBlock[],
  customText: string,
  characterContext: string,
  stageId: StageId
): string {
  const enabled = blocks
    .filter((b) => b.enabled)
    .sort((a, b) => a.order - b.order)

  const blockText = enabled.map((b) => b.value).join(', ')
  const context = [characterContext, blockText, customText].filter(Boolean).join(', ')
  const instructions: Record<StageId, { objective: string; format: string; limits: string }> = {
    ideacion: {
      objective: 'Genera una imagen conceptual del personaje que defina su identidad visual, personalidad y atmósfera.',
      format: 'Muestra su identidad, personalidad y atmósfera en una propuesta visual clara.',
      limits: 'Conserva los rasgos establecidos del personaje y evita añadir detalles contradictorios.',
    },
    sketch: {
      objective: 'Genera una imagen de boceto y entintado que establezca la estructura visual inicial del personaje.',
      format: 'Prioriza silueta, proporciones, rasgos distintivos y líneas legibles.',
      limits: 'Mantén el acabado de boceto; no lo conviertas en una ilustración final renderizada.',
    },
    turnaround: {
      objective: 'Genera una imagen tipo hoja de referencia que muestre el mismo diseño del personaje desde varios ángulos.',
      format: 'Organiza vistas frontal, lateral, trasera y tres cuartos como una hoja de referencia.',
      limits: 'Mantén constantes proporciones, vestuario, colores y accesorios entre las vistas.',
    },
    color: {
      objective: 'Genera una imagen del personaje con una paleta de color coherente y claramente aplicada.',
      format: 'Distingue colores principales, secundarios y de acento, mostrando su relación.',
      limits: 'Respeta los colores indicados y conserva la legibilidad del diseño.',
    },
    expresiones: {
      objective: 'Genera una imagen tipo hoja de expresiones que explore el rostro y las emociones del personaje.',
      format: 'Haz visibles los rasgos faciales y comunica con claridad la emoción solicitada.',
      limits: 'Conserva la identidad facial y evita cambiar edad, especie o rasgos distintivos.',
    },
    poses: {
      objective: 'Genera una imagen de cuerpo completo del personaje en una acción y pose que expresen su lenguaje corporal.',
      format: 'Muestra el cuerpo completo con una postura legible y una silueta clara.',
      limits: 'Respeta la anatomía, el equipo y las características ya definidas.',
    },
    'render-final': {
      objective: 'Genera una ilustración final del personaje, pulida y lista para presentación.',
      format: 'Integra apariencia, vestuario, equipo, pose, iluminación y composición en una imagen coherente.',
      limits: 'Conserva los detalles establecidos y evita añadir elementos que compitan con el personaje.',
    },
  }
  const instruction = instructions[stageId]

  return [
    instruction.objective,
    context,
    instruction.format,
    instruction.limits,
  ]
    .filter(Boolean)
    .join(' ')
}
