import { nanoid } from 'nanoid'
import type { CharacterBible } from '@/types/character'
import type { PromptBlock } from '@/types/prompt'
import type { WorkflowStage, StageId } from '@/types/workflow'
import { STAGE_EXTRACTION_RULES, STAGE_DEFINITIONS } from '@/data/stageTemplates'
import { resolveFieldPath } from '@/lib/resolveFieldPath'

export function autoGenerateBlocksForStage(
  character: CharacterBible,
  stageId: StageId
): PromptBlock[] {
  const rules = STAGE_EXTRACTION_RULES.filter((r) => r.stageId === stageId)
  const blocks: PromptBlock[] = []
  let order = 0

  for (const rule of rules) {
    const value = resolveFieldPath(character, rule.fieldPath)
    if (value && value.trim()) {
      blocks.push({
        id: nanoid(),
        category: rule.category,
        label: rule.label,
        value: value.trim(),
        order: order++,
        enabled: true,
      })
    }
  }

  return blocks
}

export function createEmptyStages(): WorkflowStage[] {
  return STAGE_DEFINITIONS.map((def) => ({
    id: def.id,
    index: def.index,
    blocks: [],
    customText: '',
    negativePrompt: '',
    generatedPrompt: '',
    isCompleted: false,
    isAutoGenerated: false,
    updatedAt: Date.now(),
  }))
}

export function autoPopulateAllStages(
  character: CharacterBible
): WorkflowStage[] {
  return STAGE_DEFINITIONS.map((def) => {
    const blocks = autoGenerateBlocksForStage(character, def.id)
    return {
      id: def.id,
      index: def.index,
      blocks,
      customText: '',
      negativePrompt: '',
      generatedPrompt: '',
      isCompleted: false,
      isAutoGenerated: true,
      updatedAt: Date.now(),
    }
  })
}

export function generateStagePrompt(
  blocks: PromptBlock[],
  customText: string
): string {
  const enabled = blocks
    .filter((b) => b.enabled)
    .sort((a, b) => a.order - b.order)

  const blockText = enabled.map((b) => b.value).join(', ')
  return [blockText, customText].filter(Boolean).join(', ')
}
