export const fieldDescriptions: Record<string, string> = {
  Nombre: 'Nombre principal con el que identificarás al personaje.',
  Alias: 'Nombre alternativo, apodo o título por el que también se conoce.',
  Edad: 'Edad del personaje o edad aparente si no es posible medirla.',
  Sexo: 'Describe cómo se presenta el personaje; puedes indicar género o rasgos sexuales relevantes para su diseño.',
  Especie: 'Tipo de ser al que pertenece, por ejemplo humano, elfo, androide o dragón.',
  Profesión: 'Oficio o actividad que realiza el personaje, como médica, piloto o escultor.',
  Altura: 'Estatura aproximada o relativa a otros personajes.',
  Peso: 'Peso aproximado o impresión visual de su masa corporal.',
  Constitución: 'Complexión física general, por ejemplo delgada, atlética o robusta.',
  Personalidad: 'Rasgos de carácter que influyen en cómo actúa y se expresa.',
  Historia: 'Antecedentes o acontecimientos que explican quién es el personaje.',
  Motivaciones: 'Metas o deseos que impulsan sus decisiones.',
  Miedos: 'Situaciones o cosas que el personaje teme.',
  Virtudes: 'Cualidades positivas que suelen guiar su conducta.',
  Defectos: 'Limitaciones o hábitos que pueden complicar sus decisiones.',
  Alineación: 'Orientación moral o ética, si tu mundo utiliza esta clasificación.',
  'Nivel Tecnológico': 'Grado de tecnología disponible en el entorno del personaje.',
  Universo: 'Mundo ficticio o ambientación a la que pertenece.',
  Época: 'Periodo histórico o marco temporal de la ambientación.',
  'Color de Piel': 'Tono y matices visibles de la piel.',
  'Forma del Rostro': 'Silueta general del rostro, como ovalada, redonda o angular.',
  'Estilo de Cabello': 'Corte, longitud, textura o forma del cabello.',
  'Color de Cabello': 'Color del cabello, incluidos matices o variaciones.',
  'Forma de Ojos': 'Forma o rasgo distintivo de los ojos.',
  'Color de Ojos': 'Color visible del iris.',
  Pestañas: 'Longitud, volumen o rasgos visibles de las pestañas.',
  Cejas: 'Forma, grosor o rasgos distintivos de las cejas.',
  Nariz: 'Forma o rasgos distintivos de la nariz.',
  Labios: 'Forma, volumen o rasgos distintivos de los labios.',
  Mandíbula: 'Forma o definición de la línea de la mandíbula.',
  Mentón: 'Forma o rasgo distintivo del mentón.',
  Orejas: 'Forma, tamaño o rasgos distintivos de las orejas.',
  Barba: 'Presencia, forma y longitud de la barba.',
  Bigote: 'Presencia, forma y longitud del bigote.',
  Pecas: 'Ubicación y cantidad aproximada de pecas.',
  Cuello: 'Longitud, grosor o rasgos visibles del cuello.',
  Hombros: 'Anchura, forma o rasgos distintivos de los hombros.',
  Brazos: 'Proporción, musculatura o rasgos visibles de los brazos.',
  Piernas: 'Proporción, musculatura o rasgos visibles de las piernas.',
  Manos: 'Tamaño, forma o rasgos distintivos de las manos.',
  Pies: 'Tamaño, forma o rasgos distintivos de los pies.',
  Cicatrices: 'Ubicación, forma y aspecto de las cicatrices.',
  Tatuajes: 'Diseño, ubicación y colores de los tatuajes.',
  Marcas: 'Señales visibles de nacimiento u otras marcas permanentes.',
  Quemaduras: 'Ubicación y aspecto de marcas causadas por quemaduras.',
  Prótesis: 'Prótesis o reemplazos artificiales visibles.',
  Mutaciones: 'Cambios físicos no habituales que forman parte del diseño.',
  Cabeza: 'Prendas o elementos que cubren o adornan la cabeza.',
  Torso: 'Prendas que cubren el pecho, la espalda y el abdomen.',
  Calzado: 'Tipo y aspecto del calzado.',
  Guantes: 'Tipo, material o aspecto de los guantes.',
  Capa: 'Descripción de una capa, manto u otra prenda exterior similar.',
  Cinturón: 'Tipo de cinturón y elementos que lleva sujetos.',
  Armadura: 'Piezas, cobertura y aspecto de la armadura.',
  Joyería: 'Joyas o adornos que lleva puestos.',
  Accesorios: 'Complementos visibles que no encajan en otra prenda.',
  Armas: 'Armas que porta y sus rasgos visuales principales.',
  Escudos: 'Escudos que porta, con su forma o diseño.',
  Herramientas: 'Herramientas relacionadas con sus tareas o profesión.',
  Mochila: 'Mochila, bolso o carga que lleva consigo.',
  Instrumentos: 'Instrumentos musicales u otros dispositivos que utiliza.',
  'Objetos Mágicos': 'Objetos con propiedades mágicas que lleva el personaje.',
  Tecnología: 'Dispositivos tecnológicos relevantes para su diseño.',
  Mascotas: 'Animales compañeros o criaturas que acompañan al personaje.',
  Tela: 'Tipo, textura o aspecto de las telas de su vestuario.',
  Metal: 'Tipo, acabado o color del metal presente en su diseño.',
  Cuero: 'Tipo, textura o estado del cuero utilizado.',
  Madera: 'Tipo o acabado de la madera presente en su equipo.',
  Cristal: 'Tipo, transparencia o color del cristal utilizado.',
  Piedra: 'Tipo, color o acabado de la piedra presente en el diseño.',
  Hueso: 'Uso y aspecto de piezas de hueso en vestuario o equipo.',
  Plástico: 'Tipo, color o acabado de los elementos plásticos.',
  Fibra: 'Tipo o aspecto de fibras y materiales textiles técnicos.',
  'Color Primario': 'Color dominante de la paleta del personaje.',
  'Color Secundario': 'Color que acompaña y equilibra el color dominante.',
  'Color de Acento': 'Color de contraste usado en detalles que deben destacar.',
  Temperatura: 'Sensación cálida, fría o neutra de la paleta de color.',
  Contraste: 'Diferencia de luminosidad o intensidad entre los colores.',
  Saturación: 'Intensidad apagada o vibrante de los colores.',
  'Notas sobre las referencias': 'Indica qué rasgos de las imágenes de referencia deben conservarse.',
}

export const emotionalOptionDescriptions: Record<string, string> = {
  serious: 'Expresión contenida, sin sonrisa ni gesto humorístico.',
  smiling: 'Expresión sonriente, desde una sonrisa leve hasta una amplia.',
  melancholic: 'Expresión triste o nostálgica, con energía emocional baja.',
  aggressive: 'Expresión tensa e intensa que transmite hostilidad o desafío.',
  mysterious: 'Expresión ambigua que oculta lo que siente o piensa.',
  elegant: 'Expresión refinada y controlada, con gestos deliberados.',
  innocent: 'Expresión abierta y confiada, sin señales de malicia.',
  dark: 'Tono emocional sombrío e inquietante.',
  playful: 'Expresión vivaz y traviesa, con actitud juguetona.',
  stoic: 'Expresión firme y serena que apenas revela emociones.',
  passionate: 'Expresión intensa que muestra entusiasmo o convicción.',
  serene: 'Expresión tranquila y relajada, sin tensión visible.',
}

export const visualOptionDescriptions: Record<string, string> = {
  elegant: 'Diseño refinado, equilibrado y con detalles cuidados.',
  dark: 'Estética sombría, con formas o tonos que sugieren misterio.',
  chaotic: 'Diseño irregular, dinámico y con elementos deliberadamente desordenados.',
  heroic: 'Apariencia noble y decidida que comunica valentía.',
  villain: 'Apariencia amenazante o siniestra que sugiere antagonismo.',
  mystical: 'Elementos visuales asociados con magia o fuerzas sobrenaturales.',
  military: 'Diseño funcional inspirado en uniformes, rangos o equipo militar.',
  technological: 'Apariencia con dispositivos, materiales o detalles tecnológicos.',
  natural: 'Diseño inspirado en formas, materiales o motivos de la naturaleza.',
  minimalist: 'Diseño sencillo que evita adornos y conserva solo lo esencial.',
  ornate: 'Diseño rico en adornos, patrones y detalles decorativos.',
}