import type { PromptBlock, BlockCategory } from '@/types/prompt'

export type StageId =
  | 'ideacion'
  | 'sketch'
  | 'turnaround'
  | 'color'
  | 'expresiones'
  | 'poses'
  | 'render-final'

export interface StageMeta {
  id: StageId
  index: number
  label: string
  description: string
  icon: string
  focusCategories: BlockCategory[]
}

export interface WorkflowStage {
  id: StageId
  index: number
  blocks: PromptBlock[]
  customText: string
  negativePrompt: string
  generatedPrompt: string
  isAutoGenerated: boolean
  updatedAt: number
}

export interface WorkflowProject {
  id: string
  characterId: string
  engineTemplate: string
  characterContext: string
  stages: WorkflowStage[]
  createdAt: number
  updatedAt: number
}

export interface StageExtractionRule {
  stageId: StageId
  category: BlockCategory
  label: string
  fieldPath: string
}
