import { create } from 'zustand'
import { nanoid } from 'nanoid'
import type { CharacterBible } from '@/types/character'
import type {
  WorkflowProject,
  WorkflowStage,
  StageId,
} from '@/types/workflow'
import type { PromptBlock, BlockCategory } from '@/types/prompt'
import {
  autoPopulateAllStages,
  autoGenerateBlocksForStage,
  generateStagePrompt,
} from '@/lib/autoGenerateStage'
import { STAGE_DEFINITIONS } from '@/data/stageTemplates'

interface WorkflowState {
  workflow: WorkflowProject | null
  activeStageId: StageId
  isLoading: boolean

  loadWorkflow: (characterId: string) => Promise<void>
  createWorkflow: (character: CharacterBible) => Promise<WorkflowProject>
  deleteWorkflow: (characterId: string) => Promise<void>
  setActiveStage: (stageId: StageId) => void

  autoGenerateStage: (stageId: StageId) => Promise<void>
  autoGenerateAllStages: () => Promise<void>
  markStageComplete: (stageId: StageId, completed: boolean) => void

  addBlock: (category: BlockCategory, label: string, value: string) => void
  removeBlock: (blockId: string) => void
  toggleBlock: (blockId: string) => void
  editBlock: (blockId: string, value: string) => void

  setCustomText: (text: string) => void
  setNegativePrompt: (text: string) => void
  setEngineTemplate: (templateId: string) => void

  generateStagePrompt: () => string
  generateAllPrompts: () => { stageId: StageId; label: string; prompt: string; negativePrompt: string }[]

  _updateStage: (stageId: StageId, patch: Partial<WorkflowStage>) => void
  _persist: () => Promise<void>
}

export const useWorkflowStore = create<WorkflowState>((set, get) => ({
  workflow: null,
  activeStageId: 'ideacion',
  isLoading: false,

  loadWorkflow: async (characterId) => {
    set({ isLoading: true })
    const { default: db } = await import('@/lib/db')
    const workflow = await db.workflows.get(characterId)
    set({ workflow: workflow ?? null, isLoading: false })
  },

  createWorkflow: async (character) => {
    const { default: db } = await import('@/lib/db')
    const stages = autoPopulateAllStages(character)

    const workflow: WorkflowProject = {
      id: character.id,
      characterId: character.id,
      engineTemplate: 'midjourney',
      stages,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }

    await db.workflows.add(workflow)
    set({ workflow, activeStageId: 'ideacion' })
    return workflow
  },

  deleteWorkflow: async (characterId) => {
    const { default: db } = await import('@/lib/db')
    await db.workflows.delete(characterId)
    set({ workflow: null, activeStageId: 'ideacion' })
  },

  setActiveStage: (stageId) => set({ activeStageId: stageId }),

  autoGenerateStage: async (stageId) => {
    const { workflow } = get()
    if (!workflow) return

    const { default: db } = await import('@/lib/db')
    const character = await db.characters.get(workflow.characterId)
    if (!character) return

    const blocks = autoGenerateBlocksForStage(character as CharacterBible, stageId)
    get()._updateStage(stageId, {
      blocks,
      isAutoGenerated: true,
    })
  },

  autoGenerateAllStages: async () => {
    const { workflow } = get()
    if (!workflow) return

    const { default: db } = await import('@/lib/db')
    const character = await db.characters.get(workflow.characterId)
    if (!character) return

    const stages = autoPopulateAllStages(character as CharacterBible)

    const merged = stages.map((autoStage) => {
      const existing = workflow.stages.find((s) => s.id === autoStage.id)
      if (existing && !existing.isAutoGenerated) {
        return existing
      }
      return autoStage
    })

    set((state) => {
      if (!state.workflow) return state
      return {
        workflow: {
          ...state.workflow,
          stages: merged,
          updatedAt: Date.now(),
        },
      }
    })
    await get()._persist()
  },

  markStageComplete: (stageId, completed) => {
    get()._updateStage(stageId, { isCompleted: completed })
  },

  addBlock: (category, label, value) => {
    const { activeStageId, workflow } = get()
    if (!workflow) return

    const stage = workflow.stages.find((s) => s.id === activeStageId)
    if (!stage) return

    const maxOrder = stage.blocks.reduce((max, b) => Math.max(max, b.order), -1)
    const block: PromptBlock = {
      id: nanoid(),
      category,
      label,
      value,
      order: maxOrder + 1,
      enabled: true,
    }

    get()._updateStage(activeStageId, {
      blocks: [...stage.blocks, block],
      isAutoGenerated: false,
    })
  },

  removeBlock: (blockId) => {
    const { activeStageId, workflow } = get()
    if (!workflow) return
    const stage = workflow.stages.find((s) => s.id === activeStageId)
    if (!stage) return

    get()._updateStage(activeStageId, {
      blocks: stage.blocks.filter((b) => b.id !== blockId),
    })
  },

  toggleBlock: (blockId) => {
    const { activeStageId, workflow } = get()
    if (!workflow) return
    const stage = workflow.stages.find((s) => s.id === activeStageId)
    if (!stage) return

    get()._updateStage(activeStageId, {
      blocks: stage.blocks.map((b) =>
        b.id === blockId ? { ...b, enabled: !b.enabled } : b
      ),
    })
  },

  editBlock: (blockId, value) => {
    const { activeStageId, workflow } = get()
    if (!workflow) return
    const stage = workflow.stages.find((s) => s.id === activeStageId)
    if (!stage) return

    get()._updateStage(activeStageId, {
      blocks: stage.blocks.map((b) =>
        b.id === blockId ? { ...b, value } : b
      ),
    })
  },

  setCustomText: (text) => {
    get()._updateStage(get().activeStageId, { customText: text })
  },

  setNegativePrompt: (text) => {
    get()._updateStage(get().activeStageId, { negativePrompt: text })
  },

  setEngineTemplate: (templateId) => {
    set((state) => {
      if (!state.workflow) return state
      return {
        workflow: { ...state.workflow, engineTemplate: templateId, updatedAt: Date.now() },
      }
    })
    get()._persist()
  },

  generateStagePrompt: () => {
    const { workflow, activeStageId } = get()
    if (!workflow) return ''
    const stage = workflow.stages.find((s) => s.id === activeStageId)
    if (!stage) return ''
    return generateStagePrompt(stage.blocks, stage.customText)
  },

  generateAllPrompts: () => {
    const { workflow } = get()
    if (!workflow) return []

    return workflow.stages.map((stage) => {
      const meta = STAGE_DEFINITIONS.find((d) => d.id === stage.id)!
      return {
        stageId: stage.id,
        label: meta.label,
        prompt: generateStagePrompt(stage.blocks, stage.customText),
        negativePrompt: stage.negativePrompt,
      }
    })
  },

  _updateStage: (stageId, patch) => {
    set((state) => {
      if (!state.workflow) return state
      return {
        workflow: {
          ...state.workflow,
          stages: state.workflow.stages.map((s) =>
            s.id === stageId
              ? { ...s, ...patch, updatedAt: Date.now() }
              : s
          ),
          updatedAt: Date.now(),
        },
      }
    })
    get()._persist()
  },

  _persist: async () => {
    const { workflow } = get()
    if (!workflow) return
    const { default: db } = await import('@/lib/db')
    await db.workflows.update(workflow.id, {
      stages: workflow.stages,
      engineTemplate: workflow.engineTemplate,
      updatedAt: Date.now(),
    })
  },
}))
